version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - prod-network

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: videgrenierenligne
      MYSQL_USER: webapplication
      MYSQL_PASSWORD: 653rag9T
    volumes:
      - db-prod-data:/var/lib/mysql
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql
    networks:
      - prod-network

volumes:
  db-prod-data:

networks:
  prod-network:
